### ISSUE TITLE
no unix executable when downloading from steam

### ISSUE THREAD

**Issue by SuperWeegee456** [friendlyfiregame/friendlyfiregame#24]
as stated in the title on os x the platform i'm using it won't load the game due to a missing unix executable from the source files thus the only way i can currently play the game is the bugged dev build

**Comment by headcr4sh** [comment]
Unfortunately, I don't have access to a macOS system any longer.

Steam packaging has always been a bit of a hazzle for us, because we lack most knowledge when it comes to Valve's packaging system. There are 2 alternative ways though, to play the latest stable build on macOS:

1) Head over to https://play.friendlyfiregame.com/
This is the preferred way to play the game. It works on any platform with a recent browser (Chrome-based browsers or Firefox are recommended, because they tend to render things faster and the gameplay will be smoother). Full screen mode, gamepad support, sound effects and everything else works as if running the desktop version of the game (basically, the desktop version is just a Chromium browser + the game and it's assets)

2) Download the release build of v2.3.0 from here: https://github.com/friendlyfiregame/friendlyfiregame/actions/runs/391975635
We use Github actions to automatically build versions for Windows, Linux and macOS (64 bit x86_64) and this is the run that was performed for the latest stable release.

We would love to provide a better Steam experience for Linux and macOS users.
In the meantime: let me know if any of the two options above are a viable solution at the moment if you want to play the game.

**Comment by headcr4sh** [comment]
Version 2.6.1 which has just been released on Steam and launching the game now seems to work according to reports from other macOS users. :-)
